package PRESENTACION;
import ENTIDAD.Auditoria;
import NEGOCIOS.AuditoriaService;
import java.sql.SQLException;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**** @author USUARIO */

public class frmAuditoria extends javax.swing.JFrame {

    /**
     * Creates new form frmAuditoria
     */
    public frmAuditoria() {
        initComponents(); // genera la interfaz gráfica
        cargarComboBox(); // llena el combo con los IDs de la BD
        listarTodo(); // opcional: carga la tabla al abrir
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblIdAuditoria = new javax.swing.JLabel();
        lblIpOrigen = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblAccion = new javax.swing.JLabel();
        txtIdAuditoria = new javax.swing.JTextField();
        txtIpOrigen = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtAccion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAuditoria = new javax.swing.JTable();
        btnInsertar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnListarTodo = new javax.swing.JButton();
        cmbSeleccion = new javax.swing.JComboBox<>();
        btnLimpiar = new javax.swing.JButton();
        btnActividad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("TABLA AUDITORIA");

        lblIdAuditoria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIdAuditoria.setText("ID Auditoria:");

        lblIpOrigen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIpOrigen.setText("IP Origen:");

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsuario.setText("Usuario:");

        lblAccion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAccion.setText("Acción:");

        txtIdAuditoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtIpOrigen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        txtAccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tblAuditoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID_AUDITORIA", "IP_ORIGEN", "USUARIO", "ACCIÓN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAuditoria);

        btnInsertar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnListarTodo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnListarTodo.setText("Listar Todo");
        btnListarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarTodoActionPerformed(evt);
            }
        });

        cmbSeleccion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbSeleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[seleccionar]", "Insertar", "Eliminar", "Listar Todo", "Limpiar", "Actividad" }));
        cmbSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSeleccionActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnActividad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActividad.setText("Actividad");
        btnActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActividadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(348, 348, 348)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIdAuditoria)
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdAuditoria, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(txtIpOrigen)
                            .addComponent(txtUsuario)
                            .addComponent(txtAccion)))
                    .addComponent(lblUsuario)
                    .addComponent(lblIpOrigen)
                    .addComponent(lblAccion))
                .addGap(158, 276, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(286, 286, 286))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(btnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnListarTodo)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiar)
                                .addGap(18, 18, 18)
                                .addComponent(btnActividad))
                            .addComponent(btnInsertar))
                        .addGap(168, 168, 168))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cmbSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(389, 389, 389))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdAuditoria)
                            .addComponent(txtIdAuditoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblUsuario)
                                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtIpOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblIpOrigen))
                                .addGap(51, 51, 51)))))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccion)
                    .addComponent(txtAccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertar)
                    .addComponent(btnEliminar)
                    .addComponent(btnListarTodo)
                    .addComponent(btnLimpiar)
                    .addComponent(btnActividad))
                .addGap(64, 64, 64)
                .addComponent(cmbSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        try {
        Auditoria a = new Auditoria(
            Integer.parseInt(txtIdAuditoria.getText()),
            txtIpOrigen.getText(),
            txtUsuario.getText(),
            txtAccion.getText()
        );
        AuditoriaService service = new AuditoriaService();
        service.registrarAuditoria(a);
        JOptionPane.showMessageDialog(this, "Registro insertado correctamente");
        
        // Actualizar combo box con nuevo ID
        cmbSeleccion.addItem(String.valueOf(a.getIdAuditoria()));
        
        listarTodo();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error al insertar: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
        int id = Integer.parseInt(txtIdAuditoria.getText());
        AuditoriaService service = new AuditoriaService();
        service.eliminarAuditoria(id);
        JOptionPane.showMessageDialog(this, "Registro eliminado correctamente");
        
        // Quitar ID del combo
        cmbSeleccion.removeItem(String.valueOf(id));
        
        listarTodo();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error al eliminar: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnListarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarTodoActionPerformed
        listarTodo();
}

private void listarTodo() {
    try {
        AuditoriaService service = new AuditoriaService();
        List<Auditoria> lista = service.listarAuditorias();
        DefaultTableModel modelo = (DefaultTableModel) tblAuditoria.getModel();
        modelo.setRowCount(0); // limpiar tabla
        for (Auditoria a : lista) {
            modelo.addRow(new Object[]{
                a.getIdAuditoria(),
                a.getIpOrigen(),
                a.getUsuario(),
                a.getAccion()
            });
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error al listar: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnListarTodoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtIdAuditoria.setText("");
        txtIpOrigen.setText("");
        txtUsuario.setText("");
        txtAccion.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActividadActionPerformed
        try {
        int id = Integer.parseInt((String) cmbSeleccion.getSelectedItem());
        AuditoriaService service = new AuditoriaService();
        Auditoria a = service.buscarAuditoria(id);
        if (a != null) {
            txtIdAuditoria.setText(String.valueOf(a.getIdAuditoria()));
            txtIpOrigen.setText(a.getIpOrigen());
            txtUsuario.setText(a.getUsuario());
            txtAccion.setText(a.getAccion());
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró el registro");
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error al buscar: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnActividadActionPerformed

    private void cmbSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSeleccionActionPerformed
        try {
        AuditoriaService service = new AuditoriaService();
        List<Auditoria> lista = service.listarAuditorias();
        cmbSeleccion.removeAllItems();
        for (Auditoria a : lista) {
            cmbSeleccion.addItem(String.valueOf(a.getIdAuditoria()));
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error al cargar combo: " + ex.getMessage());
    }
    }//GEN-LAST:event_cmbSeleccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAuditoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAuditoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAuditoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAuditoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAuditoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActividad;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnListarTodo;
    private javax.swing.JComboBox<String> cmbSeleccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAccion;
    private javax.swing.JLabel lblIdAuditoria;
    private javax.swing.JLabel lblIpOrigen;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTable tblAuditoria;
    private javax.swing.JTextField txtAccion;
    private javax.swing.JTextField txtIdAuditoria;
    private javax.swing.JTextField txtIpOrigen;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    private void cargarComboBox() {
    try {
        AuditoriaService service = new AuditoriaService();
        List<Auditoria> lista = service.listarAuditorias();
        cmbSeleccion.removeAllItems();
        for (Auditoria a : lista) {
            cmbSeleccion.addItem(String.valueOf(a.getIdAuditoria()));
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error al cargar combo: " + ex.getMessage());
    }
    }
    }