package PRESENTACION;
import ENTIDAD.Contrato;
import NEGOCIOS.ContratoService;
import java.sql.SQLException;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel; // Para mostrar mensajes de error

/**
 * @author Aaron Culli Lazarte
 * Colaborador: Sebastián Huaripaucar Anaya
 */
public class frmContrato extends javax.swing.JFrame {

    // Instancia única del servicio para toda la clase
    ContratoService servicio = new ContratoService();

    public frmContrato() {
        initComponents();
        this.setLocationRelativeTo(null); // Centrar ventana
        cargarComboBox();   // Llena el combo al iniciar
        listar();           // Carga la tabla al iniciar
    }

    public void listar() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Cliente");
        modelo.addColumn("Tipo");
        modelo.addColumn("Fecha Inicio");
        modelo.addColumn("Fecha Fin");

        // Usamos servicio.listar() que devuelve List<Contrato>
        List<Contrato> lista = servicio.listar();
        for (Contrato c : lista) {
            modelo.addRow(new Object[]{
                c.getIdContrato(),
                c.getIdCliente(),
                c.getTipo(),
                c.getFechaInicio(),
                c.getFechaFin()
            });
        }
        tblContrato.setModel(modelo);
    }

    public void cargarComboBox() {
        try {
            cboFiltroId.removeAllItems();
            cboFiltroId.addItem("Seleccionar");

            // Usamos el método listar() del servicio de Sebastián
            List<Contrato> lista = servicio.listar();

            for (Contrato item : lista) {
                // Agregamos el ID del contrato al ComboBox
                cboFiltroId.addItem(String.valueOf(item.getIdContrato()));
            }
        } catch (Exception e) {
            System.err.println("Error al cargar ComboBox: " + e.getMessage());
        }
    }

    private void filtrarTablaPorId(int id) {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Cliente");
        modelo.addColumn("Tipo");
        modelo.addColumn("Fecha Inicio");
        modelo.addColumn("Fecha Fin");

        Contrato c = servicio.buscar(id);
        if (c != null) {
            modelo.addRow(new Object[]{
                c.getIdContrato(),
                c.getIdCliente(),
                c.getTipo(),
                c.getFechaInicio(),
                c.getFechaFin()
            });
        }
        tblContrato.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistrar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnReporteCliente = new javax.swing.JButton();
        txtIdContrato = new javax.swing.JTextField();
        txtIdCliente = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblContrato = new javax.swing.JTable();
        txtFechaInicio = new javax.swing.JTextField();
        txtFechaFin = new javax.swing.JTextField();
        lblIdContrato = new javax.swing.JLabel();
        lblIdCliente = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblFechaInicio = new javax.swing.JLabel();
        lblFechaFin = new javax.swing.JLabel();
        lblCONTRATO = new javax.swing.JLabel();
        cboFiltroId = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnListar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnReporteCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReporteCliente.setText("Reporte Cliente");
        btnReporteCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteClienteActionPerformed(evt);
            }
        });

        txtIdContrato.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtIdContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdContratoActionPerformed(evt);
            }
        });

        txtIdCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtIdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdClienteActionPerformed(evt);
            }
        });

        txtTipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tblContrato.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblContrato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Tipo", "Fecha Inicio", "Fecha Fin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblContrato);

        txtFechaInicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtFechaFin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblIdContrato.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIdContrato.setText("ID Contrato:");

        lblIdCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIdCliente.setText("ID Cliente:");

        lblTipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTipo.setText("Tipo");

        lblFechaInicio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFechaInicio.setText("Fecha Inicio:");

        lblFechaFin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFechaFin.setText("Fecha Fin:");

        lblCONTRATO.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        lblCONTRATO.setText("TABLA CONTRATO");

        cboFiltroId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cboFiltroId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboFiltroId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboFiltroIdItemStateChanged(evt);
            }
        });
        cboFiltroId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboFiltroIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRegistrar)
                .addGap(32, 32, 32)
                .addComponent(btnActualizar)
                .addGap(24, 24, 24)
                .addComponent(btnEliminar)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnListar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReporteCliente)
                .addGap(90, 90, 90))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIdContrato)
                                    .addComponent(lblIdCliente)
                                    .addComponent(lblTipo)
                                    .addComponent(lblFechaInicio)
                                    .addComponent(lblFechaFin))
                                .addGap(91, 91, 91)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(txtFechaInicio)
                                    .addComponent(txtTipo)
                                    .addComponent(txtIdCliente)
                                    .addComponent(txtIdContrato)))
                            .addComponent(lblCONTRATO)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(456, 456, 456)
                        .addComponent(cboFiltroId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblCONTRATO, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblIdContrato)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdCliente)
                            .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTipo)
                    .addComponent(txtFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaInicio)
                    .addComponent(txtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaFin)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar)
                    .addComponent(btnBuscar)
                    .addComponent(btnReporteCliente)
                    .addComponent(btnListar)
                    .addComponent(btnLimpiar))
                .addGap(18, 18, 18)
                .addComponent(cboFiltroId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdContratoActionPerformed
        // Vacio
    }//GEN-LAST:event_txtIdContratoActionPerformed

    private void txtIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdClienteActionPerformed
        // Vacio
    }//GEN-LAST:event_txtIdClienteActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        Contrato c = new Contrato(
        Integer.parseInt(txtIdContrato.getText()),
        Integer.parseInt(txtIdCliente.getText()),
        txtTipo.getText(),
        txtFechaInicio.getText(),
        txtFechaFin.getText()
        );

        servicio.guardar(c);
        listar();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        Contrato c = new Contrato(
        Integer.parseInt(txtIdContrato.getText()),
        Integer.parseInt(txtIdCliente.getText()),
        txtTipo.getText(),
        txtFechaInicio.getText(),
        txtFechaFin.getText()
        );

        servicio.actualizar(c);
        listar();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int id = Integer.parseInt(txtIdContrato.getText());
        servicio.eliminar(id);
        listar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int id = Integer.parseInt(txtIdContrato.getText());
        Contrato c = servicio.buscar(id);

        if (c != null) {
        txtIdCliente.setText(String.valueOf(c.getIdCliente()));
        txtTipo.setText(c.getTipo());
        txtFechaInicio.setText(c.getFechaInicio());
        txtFechaFin.setText(c.getFechaFin());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        listar();
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtIdContrato.setText("");
        txtIdCliente.setText("");
        txtTipo.setText("");
        txtFechaInicio.setText("");
        txtFechaFin.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnReporteClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteClienteActionPerformed
        int idCliente = Integer.parseInt(txtIdCliente.getText());

        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Cliente");
        modelo.addColumn("Tipo");
        modelo.addColumn("Fecha Inicio");
        modelo.addColumn("Fecha Fin");

        for (Contrato c : servicio.dao.listarPorCliente(idCliente)) {
        modelo.addRow(new Object[]{
            c.getIdContrato(),
            c.getIdCliente(),
            c.getTipo(),
            c.getFechaInicio(),
            c.getFechaFin()
        });
    }

        tblContrato.setModel(modelo);
    }//GEN-LAST:event_btnReporteClienteActionPerformed

    private void cboFiltroIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFiltroIdActionPerformed
        // Vacio
    }//GEN-LAST:event_cboFiltroIdActionPerformed

    private void cboFiltroIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboFiltroIdItemStateChanged
        if (java.awt.event.ItemEvent.SELECTED == evt.getStateChange()) {
            String seleccionado = cboFiltroId.getSelectedItem().toString();
            
            if (!seleccionado.equals("Seleccionar")) {
                int id = Integer.parseInt(seleccionado);
                filtrarTablaPorId(id);
            } else {
                listar(); // Si elige "Seleccionar", mostramos todo
            }
        } else {
        }
    }//GEN-LAST:event_cboFiltroIdItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmContrato().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnReporteCliente;
    private javax.swing.JComboBox<String> cboFiltroId;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCONTRATO;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblIdCliente;
    private javax.swing.JLabel lblIdContrato;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTable tblContrato;
    private javax.swing.JTextField txtFechaFin;
    private javax.swing.JTextField txtFechaInicio;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtIdContrato;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables

}
