package PRESENTACION;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import NEGOCIOS.SeguimientoFacturaControlador;
import ENTIDAD.SeguimientoFactura;

public class FrmSeguimientoFactura extends javax.swing.JFrame {
    private void generarPDF() {
    try {
        com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
        com.itextpdf.text.pdf.PdfWriter.getInstance(doc, new java.io.FileOutputStream("reporte_seguimiento.pdf"));

        doc.open();

        // LOGO
        try {
            com.itextpdf.text.Image logo = com.itextpdf.text.Image.getInstance("src/imagen/Ferreyros.png");
            logo.scaleToFit(100, 100);
            logo.setAlignment(com.itextpdf.text.Image.ALIGN_CENTER);
            doc.add(logo);
        } catch (Exception e) {
            System.out.println("Logo no encontrado");
        }

        // TITULO
        com.itextpdf.text.Paragraph titulo = new com.itextpdf.text.Paragraph(
                "REPORTE DE SEGUIMIENTO",
                com.itextpdf.text.FontFactory.getFont(
                        com.itextpdf.text.FontFactory.HELVETICA_BOLD, 16
                )
        );
        titulo.setAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
        doc.add(titulo);

        doc.add(new com.itextpdf.text.Paragraph("\n"));

        // TABLA
        com.itextpdf.text.pdf.PdfPTable tablaPDF = new com.itextpdf.text.pdf.PdfPTable(6);

        tablaPDF.addCell("Factura");
        tablaPDF.addCell("Pedido");
        tablaPDF.addCell("Transacción");
        tablaPDF.addCell("Empleado");
        tablaPDF.addCell("Estado");
        tablaPDF.addCell("Sucursal");

        for (int i = 0; i < tablaSeguimiento.getRowCount(); i++) {
            tablaPDF.addCell(tablaSeguimiento.getValueAt(i, 0).toString());
            tablaPDF.addCell(tablaSeguimiento.getValueAt(i, 1).toString());
            tablaPDF.addCell(tablaSeguimiento.getValueAt(i, 2).toString());
            tablaPDF.addCell(tablaSeguimiento.getValueAt(i, 3).toString());
            tablaPDF.addCell(tablaSeguimiento.getValueAt(i, 4).toString());
            tablaPDF.addCell(tablaSeguimiento.getValueAt(i, 5).toString());
        }

        doc.add(tablaPDF);
        doc.close();

        JOptionPane.showMessageDialog(this, "PDF generado correctamente");

    } catch (Exception e) {
        e.printStackTrace();
    }
}
private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmSeguimientoFactura.class.getName());
    SeguimientoFacturaControlador c = new SeguimientoFacturaControlador();

    public FrmSeguimientoFactura() {
        initComponents();
        this.setLocationRelativeTo(null); // Centrar ventana
        cargarCombos(); // Cargar datos iniciales
        listar(); // Mostrar datos en la tabla al iniciar
    }
    
     private void cargarCombos() {
        cbFactura.removeAllItems();
        cbPedido.removeAllItems();
        cbTransaccion.removeAllItems();
        cbEmpleado.removeAllItems();

        // Usamos el controlador para traer datos reales de Oracle
        for (String f : c.listarFacturas()) cbFactura.addItem(f);
        for (String p : c.listarPedidos()) cbPedido.addItem(p);
        for (String t : c.listarTransacciones()) cbTransaccion.addItem(t);
        for (String e : c.listarEmpleados()) cbEmpleado.addItem(e);
    }

    private void listar() {
        llenarTabla(c.listar());
    }

    public void llenarTabla(ArrayList<SeguimientoFactura> lista) {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new Object[]{
            "Factura ID", "Pedido ID", "Transacción", "Empleado", "Estado", "Sucursal"
        });

        for (SeguimientoFactura s : lista) {
            modelo.addRow(new Object[]{
                s.getIdFactura(),
                s.getIdPedido(),
                s.getIdTransaccion(),
                s.getIdEmpleado(),
                s.getEstado(),
                s.getSucursal()
            });
        }
        tablaSeguimiento.setModel(modelo);
    }

    private SeguimientoFactura capturarDatos() {
        SeguimientoFactura s = new SeguimientoFactura();
        s.setIdFactura(cbFactura.getSelectedItem().toString());
        s.setIdPedido(cbPedido.getSelectedItem().toString());
        s.setIdTransaccion(cbTransaccion.getSelectedItem().toString());
        s.setIdEmpleado(cbEmpleado.getSelectedItem().toString());
        // Valores fijos para los nuevos campos si no tienes combos aún
        s.setEstado("PENDIENTE");
        s.setSucursal("LIMA - CENTRAL");
        return s;
    }
   
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnReporteGeneral = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaSeguimiento = new javax.swing.JTable();
        cbFactura = new javax.swing.JComboBox<>();
        cbPedido = new javax.swing.JComboBox<>();
        cbTransaccion = new javax.swing.JComboBox<>();
        cbEmpleado = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnReporteFactura = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnPDF = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("FACTURA ID");

        jLabel3.setText("PEDIDO ID");

        jLabel4.setText("TRANSACCION ID");

        jLabel5.setText("EMPLEADO ID");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnReporteGeneral.setText("Mostrar todo");
        btnReporteGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteGeneralActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        tablaSeguimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablaSeguimiento);

        cbFactura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFacturaActionPerformed(evt);
            }
        });

        cbPedido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbTransaccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTransaccionActionPerformed(evt);
            }
        });

        cbEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seguimiento de tu factura");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Ferreyros.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnReporteFactura.setText("Filtrar");
        btnReporteFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteFacturaActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnPDF.setText("PDF");
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbPedido, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbFactura, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbTransaccion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addGap(45, 45, 45)
                                .addComponent(btnActualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnListar)
                                .addGap(41, 41, 41)
                                .addComponent(btnLimpiar)
                                .addGap(55, 55, 55)
                                .addComponent(btnEliminar)
                                .addGap(26, 26, 26))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(btnReporteGeneral)
                        .addGap(44, 44, 44)
                        .addComponent(btnReporteFactura)
                        .addGap(61, 61, 61)
                        .addComponent(btnPDF)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(6, 6, 6)
                        .addComponent(cbTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminar)
                    .addComponent(btnListar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnActualizar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReporteGeneral)
                    .addComponent(btnReporteFactura)
                    .addComponent(btnPDF))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbTransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTransaccionActionPerformed
       
    }//GEN-LAST:event_cbTransaccionActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {                                           
    
   if (c.guardar(capturarDatos())) {
            JOptionPane.showMessageDialog(this, "Guardado exitosamente");
            listar();
        } else {
            JOptionPane.showMessageDialog(this, "Error: El ID ya existe");
        }
    }

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {                                          
      llenarTabla(c.listar());
}
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {                                            
     String id = cbFactura.getSelectedItem().toString();
        if (c.eliminar(id)) {
            JOptionPane.showMessageDialog(this, "Registro eliminado");
            listar();
        }
    }

 

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
     cbFactura.setSelectedIndex(0);
        cbPedido.setSelectedIndex(0);
        cbTransaccion.setSelectedIndex(0);
        cbEmpleado.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnReporteGeneralActionPerformed(java.awt.event.ActionEvent evt) {                                                  
      listar();
    

} 

    private void btnReporteFacturaActionPerformed(java.awt.event.ActionEvent evt) {                                                  
     String id = cbFactura.getSelectedItem().toString();
        llenarTabla(c.listarPorFactura(id));
}

    private void cbFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFacturaActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
     if (c.actualizar(capturarDatos())) {
            JOptionPane.showMessageDialog(this, "Actualizado correctamente");
            listar();
        } else {
            JOptionPane.showMessageDialog(this, "Error al actualizar");
        }
    
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
       generarPDF();
    }//GEN-LAST:event_btnPDFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmSeguimientoFactura().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnPDF;
    private javax.swing.JButton btnReporteFactura;
    private javax.swing.JButton btnReporteGeneral;
    private javax.swing.JComboBox<String> cbEmpleado;
    private javax.swing.JComboBox<String> cbFactura;
    private javax.swing.JComboBox<String> cbPedido;
    private javax.swing.JComboBox<String> cbTransaccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tablaSeguimiento;
    // End of variables declaration//GEN-END:variables

}   // --- MÉTODOS ÚNICOS (SOLO UNO DE CADA UNO) ---

